# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-30 22:41
from __future__ import unicode_literals

import Auction_system.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auction_system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to=Auction_system.models.getImage),
        ),
        migrations.AlterField(
            model_name='product',
            name='purdate',
            field=models.DateField(default=None),
        ),
    ]
